language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm install
  - npm run lint
  - npm run prod
deploy:
  provider: pages
  skip_cleanup: true
  fqdn: developers-tmp.streamjar.tv
  github_token: $githubToken
  local_dir: dist
  on:
    branch: gh-pages
