language: node_js
node_js:
  - "stable"
before_install:
  - npm install netlify-cli -g
cache:
  directories:
  - node_modules
script:
  - npm install
  - npm run lint
  - npm run prod
deploy:
  provider: script
  script: netlify deploy --prod -dir=dist
  skip_cleanup: true
  on:
    branch: master
